package com.opentrainer.openai.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Represents a training plan generated by OpenAI
 */
public record TrainingPlan(
    @JsonProperty("plan_id")
    String planId,
    
    @JsonProperty("user_id")
    String userId,
    
    @JsonProperty("title")
    String title,
    
    @JsonProperty("description")
    String description,
    
    @JsonProperty("duration_weeks")
    Integer durationWeeks,
    
    @JsonProperty("difficulty_level")
    String difficultyLevel,
    
    @JsonProperty("weekly_schedule")
    List<WeeklySchedule> weeklySchedule,
    
    @JsonProperty("nutrition_guidelines")
    String nutritionGuidelines,
    
    @JsonProperty("safety_considerations")
    List<String> safetyConsiderations
) {
    
    public record WeeklySchedule(
        @JsonProperty("week")
        Integer week,
        
        @JsonProperty("workouts")
        List<Workout> workouts
    ) {}
    
    public record Workout(
        @JsonProperty("day")
        String day,
        
        @JsonProperty("type")
        String type,
        
        @JsonProperty("duration_minutes")
        Integer durationMinutes,
        
        @JsonProperty("exercises")
        List<Exercise> exercises,
        
        @JsonProperty("rest_periods")
        String restPeriods
    ) {}
    
    public record Exercise(
        @JsonProperty("name")
        String name,
        
        @JsonProperty("sets")
        Integer sets,
        
        @JsonProperty("reps")
        String reps,
        
        @JsonProperty("weight")
        String weight,
        
        @JsonProperty("instructions")
        String instructions
    ) {}
}